### ISSUE TITLE
Unclear which websocket package is required

### ISSUE THREAD

**Issue by z** [aclytle/samsung_tv_ip_remote#1]
I've tried running `samsung-client.py` with websockets (as instructed by the `README`: `pip3 install websockets`)

``` bash
$ ./samsung-client.py 192.168.1.10 menu
Traceback (most recent call last):
  File "./samsung-client.py", line 3, in <module>
    import websocket
ImportError: No module named 'websocket'
```

I adjusted `import websocket` to `import websockets` in the top of samsung-client.py (not that I expected that to work, which it didn't):

``` bash
$ ./samsung-client.py 192.168.1.10 menu
b'ZYptOBJ-6VZY7-tpAPCH:60:60:websocket,htmlfile,xhr-polling,jsonp-polling'
ZYptOBJ-6VZY7-tpAPCH
ws://192.168.1.10:8000/socket.io/1/websocket/ZYptOBJ-6VZY7-tpAPCH
Traceback (most recent call last):
  File "./samsung-client.py", line 48, in <module>
    ws = connect(ip)
  File "./samsung-client.py", line 27, in connect
    ws = websocket.WebSocket()
NameError: name 'websocket' is not defined
```

So I figured you must have meant 'websocket'

`pip3 install websocket`:

``` bash
$ ./samsung-client.py 192.168.1.10 menu
b'4t3nEjZiG47iYExWAPCG:60:60:websocket,htmlfile,xhr-polling,jsonp-polling'
4t3nEjZiG47iYExWAPCG
ws://192.168.1.10:8000/socket.io/1/websocket/4t3nEjZiG47iYExWAPCG
Traceback (most recent call last):
  File "./samsung-client.py", line 48, in <module>
    ws = connect(ip)
  File "./samsung-client.py", line 27, in connect
    ws = websocket.WebSocket()
TypeError: __init__() missing 3 required positional arguments: 'environ', 'socket', and 'rfile'
```

I appreciate the work you've put into understanding the new protocol, I've gotten part way there with a javascript implementation, having your tool as a reference would help me get it all the way there.

**Comment by z** [comment]
I just found the package: https://pypi.python.org/pypi/websocket-client

`pip3 install websocket-client`

However, my TV (UN32H5500) does not react. Are there additional steps I need to take for pairing?

Using mitmproxy with a phone app, I was able to find some additional URLs that bring up the "Connection Request" dialog with a PIN to verify. Though I'm still trying to reverse engineer the payloads.

```
http://192.168.1.10:8080/ws/pairing?step=0&app_id=12345&device_id=xx:xx:xx:xx:xx:xx
http://192.168.1.10:8080/ws/pairing?step=1&app_id=12345&device_id=xx:xx:xx:xx:xx:xx
http://192.168.1.10:8080/ws/pairing?step=2&app_id=12345&device_id=xx:xx:xx:xx:xx:xx
http://192.168.1.15:8080/ws/remote/connect
```

**Comment by aclytle** [comment]
I'm still working on reverse engineering the payloads. There's some sort of key applied to the payloads to encode them for a specific session. I've only been able to get it to work after connecting the phone app then retransmitting the payloads.

**Comment by z** [comment]
Okay, thanks for clarifying, we're on the same page in that regard then.

step=0 brings up the connect dialog so it only makes sense that this pin is used somewhere in the payload that's sent from the device in step=1

The first part of the "GeneratorServerHello" payload is always the same for me:

```
010200000000000000008A00000006363534333231
```

The second part is 256 hex characters

```
99E54C69CE136F1F1CFB7CE76BF96B2721CDA91358930EA6C2FC31AF5A62AC1C44FD3A1656F8422CAA7929DA9DA2FE4FB7274EA05027833A16C28B8CEE1C66DB2D29DB2B0A6E7EB63D76879559C3049C280B97FEC9798F667ECC06677A49F4A99FAA69691420963DB5FC89C4FF415DAFCE4730C7DF6F1E07BC2B2433E380C8
```

The last is always ten 0s

```
0000000000
```

Similarly, the GeneratorClientHello response from the TV always contains a consistent string of HEX in the beginning, 296 characters in the middle and ten 0s at the end.

Are you seeing the same?

I believe the following information could be used in generating the hash but I haven't been able to confirm any of it yet:
- date/time
- device id
- app id
- user agent

Please let me know if you make any more progress. I'll continue to tinker myself. Thanks :+1:

**Comment by aclytle** [comment]
To answer your original question, I'm using websocket-client from pypi. pip install websocket-client

**Comment by timelery** [comment]
I successfully decompiled the smart view app for windows and android. I have visibility to all the pairing and communication logic including how the calls are encrypted and decrypted. If you may find it useful I can email it to you.

**Comment by z** [comment]
:+1:  @timelery z@xnz.me

**Comment by timelery** [comment]
Quick update. The Smart View package I worked with was the newest version. It turns out Samsung removed the remote control functionality from it so that is why I did not see any references. I dug through the net for a few days and found a link to the old version from 2014 that contained remote control functionality and decompiled that one. 

Here is the link to the working VS project files. 

https://drive.google.com/open?id=0B4rFn8xXaiKsU2pleHFxcVlpNE0

I am working on a small console app to send remote control commands so i can use it to work with calls from my Z wave network via smart things. Whenever I have something substantial I will share it.

If someone beats me to it I encourage you to share it as well.

**Comment by z** [comment]
Nice, thanks for the update.

**Comment by Bradley225** [comment]
@timelery b.mcdonagh@sky.com

**Comment by ttonyh** [comment]
@timelery Can you update the google drive link that you posted, please? Looks like it's down.

**Comment by jimangelov** [comment]
Hello, I was able to find where the encryption is defined. In short Samsung have ported multiscreen api to C# for Smart View on Windows PC. They are using BouncyCastle.Crypto for C# so in "multiscreen-windows-api-csharp.dll" there is Class "ChannelWebsocketConnection : ChannelConnection" that have the Public Key  
private static string TV_PUB_KEY
I can provide the whole decompiled version if someone is able to make use of it.

**Comment by timelery** [comment]
Yes, please provide it

**Comment by jim-022** [comment]
Actually the encryption is not even needed for remote control payloads. They are using their own algorithm to do Encoding and deserialization of the json. Unfortunately... decompiles are not doing great job.

**Comment by ttonyh** [comment]
Has anyone been able to successful control their latest generation, Tizen based Samaung TV, via IP?

**Comment by kfkkail** [comment]
FYI. Tried this on my Samsung TV UN65HU8550FXZA and it didn't react either. Has anyone made progress here? @z Seems like I'm in the same situation as you. I can get the connect dialog to come up with the pin, but can't get past that.

**Comment by timelery** [comment]
My command line Samsung remote control has been uploaded to Github. This works on the newest models that use the new encrypted protocol. 

[https://github.com/timelery/NewestSamsung-RemoteControl](https://github.com/timelery/NewestSamsung-RemoteControl)

Please provide feedback.

Thank you,
Tim

**Comment by ttonyh** [comment]
Thanks @timelery  I tried running several weeks ago, it and it kind of worked for me. I'm sure if I played around with it a bit more, I could get it to do what I want. My biggest problem is that It's written in .Net. I tried porting it to Mono so I could use it on a Raspberry Pi but it wouldn't compile. I'm sure you or someone who has more experience with .Net than I do, could probably get it to work. So, what I'm asking is, is there any chance you could modify it so that it will compile and run in Mono?

Thanks again,
